### ISSUE TITLE
dockerfile doesnt expose any ports

### ISSUE THREAD

**Issue by kungfoome** [Roxedus/docker-conreq#6] opened 2021-03-10 01:02 UTC
Dockerfile doesn't expose any ports. Looks like it should expose 8000

**Comment by Roxedus** [comment] 2021-03-10 02:00
It's not a bug, it doesn't break core docker functionality. You can vaguely argue it's against best practice.

**Comment by kungfoome** [comment] 2021-03-10 02:29
@Roxedus thats fine, but the only option is to report a bug

**Comment by Archmonger** [comment] 2021-04-12 00:56
Resolved in latest develop commits

**Closed as completed by Archmonger** 2021-04-12 00:56 UTC
